// <auto-generated />
using System;
using DocPrep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocPrep.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocPrepDbContext))]
    [Migration("20261003163403_ElevenLabsAgentInterviews")]
    partial class ElevenLabsAgentInterviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("docprep")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocPrep.Domain.Access.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessGrantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedDestination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitProcessId");

                    b.ToTable("delivery_attempts", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Access.PatientAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<string>("LinkTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitCodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LinkTokenHash")
                        .IsUnique();

                    b.HasIndex("VisitCodeHash")
                        .IsUnique();

                    b.HasIndex("VisitProcessId");

                    b.ToTable("patient_access_grants", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Access.PatientIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPesel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey")
                        .IsUnique();

                    b.ToTable("patients", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.AgentInterview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalReport")
                        .HasColumnType("text");

                    b.Property<string>("InterviewType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StructuredDataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitProcessId")
                        .IsUnique();

                    b.ToTable("agent_interviews", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.AgentInterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscriptJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId");

                    b.HasIndex("ProviderConversationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("agent_interview_sessions", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reaction")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("allergies", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.ChronicCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("chronic_conditions", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Clarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("clarifications", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.ExternalWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalEventId")
                        .IsUnique();

                    b.ToTable("external_webhook_events", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.InterviewAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("interview_answers", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.InterviewDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsultationReason")
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitProcessId")
                        .IsUnique();

                    b.ToTable("interview_drafts", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.InterviewInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSessionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionCount")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("interview_invitations", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dose")
                        .HasColumnType("text");

                    b.Property<string>("DoseState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("medications", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.PatientQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("patient_questions", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Symptom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DailyImpact")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("date");

                    b.Property<string>("StartedOnState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("symptoms", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.SymptomTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("Period")
                        .HasColumnType("text");

                    b.Property<Guid>("SymptomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SymptomId");

                    b.ToTable("symptom_timeline", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Observations.ObservationEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObservationProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SourceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFragment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceReportVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceVisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObservationProposalId");

                    b.ToTable("observation_evidence", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Observations.ObservationProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientEditedText")
                        .HasColumnType("text");

                    b.Property<string>("SymptomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewDraftId");

                    b.ToTable("observation_proposals", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Privacy.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitProcessId", "OccurredAt");

                    b.ToTable("audit_events", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Privacy.DeletionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("PatientCorrelationKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByFacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("deletion_requests", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Reports.ReportEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SourceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFragment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceReportVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceVisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportVersionId");

                    b.ToTable("report_evidence", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Reports.ReportVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConfirmedIncomplete")
                        .HasColumnType("boolean");

                    b.Property<int>("CreatedFromDraftRevision")
                        .HasColumnType("integer");

                    b.Property<string>("JsonSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PdfData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PdfSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PdfStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitProcessId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("report_versions", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Sharing.SharingConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitProcessId", "RevokedAt");

                    b.ToTable("sharing_consents", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupplementationQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupplementationQuestionId")
                        .IsUnique();

                    b.ToTable("supplementation_answers", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AskedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AskedByClinicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupplementationRoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupplementationRoundId");

                    b.ToTable("supplementation_questions", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpenedByClinicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VisitProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitProcessId");

                    b.ToTable("supplementation_rounds", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Tenancy.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("facilities", "docprep");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Przychodnia Demo"
                        });
                });

            modelBuilder.Entity("DocPrep.Domain.Tenancy.StaffRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("staff_refresh_tokens", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Tenancy.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacilityId");

                    b.ToTable("staff_users", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Visits.VisitProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedClinicianId")
                        .HasColumnType("text");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ContactChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalVisitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LatestApprovedVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LatestSharedVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ServiceExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientIdentityId");

                    b.HasIndex("FacilityId", "ExternalVisitId")
                        .IsUnique();

                    b.ToTable("visits", "docprep");
                });

            modelBuilder.Entity("DocPrep.Domain.Access.DeliveryAttempt", b =>
                {
                    b.HasOne("DocPrep.Domain.Visits.VisitProcess", null)
                        .WithMany()
                        .HasForeignKey("VisitProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Access.PatientAccessGrant", b =>
                {
                    b.HasOne("DocPrep.Domain.Visits.VisitProcess", null)
                        .WithMany()
                        .HasForeignKey("VisitProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.AgentInterview", b =>
                {
                    b.HasOne("DocPrep.Domain.Visits.VisitProcess", null)
                        .WithMany()
                        .HasForeignKey("VisitProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.AgentInterviewSession", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.AgentInterview", null)
                        .WithMany()
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocPrep.Domain.Tenancy.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Allergy", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany("Allergies")
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.ChronicCondition", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany("ChronicConditions")
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Clarification", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany("Clarifications")
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.InterviewAnswer", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany("Answers")
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.InterviewDraft", b =>
                {
                    b.HasOne("DocPrep.Domain.Visits.VisitProcess", null)
                        .WithOne()
                        .HasForeignKey("DocPrep.Domain.Interviews.InterviewDraft", "VisitProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.InterviewInvitation", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.AgentInterview", null)
                        .WithMany()
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Medication", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany("Medications")
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.PatientQuestion", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany("PatientQuestions")
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Symptom", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany("Symptoms")
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.SymptomTimelineEntry", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.Symptom", null)
                        .WithMany("Timeline")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Observations.ObservationEvidence", b =>
                {
                    b.HasOne("DocPrep.Domain.Observations.ObservationProposal", null)
                        .WithMany("Evidence")
                        .HasForeignKey("ObservationProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Observations.ObservationProposal", b =>
                {
                    b.HasOne("DocPrep.Domain.Interviews.InterviewDraft", null)
                        .WithMany()
                        .HasForeignKey("InterviewDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Reports.ReportEvidence", b =>
                {
                    b.HasOne("DocPrep.Domain.Reports.ReportVersion", null)
                        .WithMany()
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Reports.ReportVersion", b =>
                {
                    b.HasOne("DocPrep.Domain.Visits.VisitProcess", null)
                        .WithMany()
                        .HasForeignKey("VisitProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Sharing.SharingConsent", b =>
                {
                    b.HasOne("DocPrep.Domain.Visits.VisitProcess", null)
                        .WithMany()
                        .HasForeignKey("VisitProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationAnswer", b =>
                {
                    b.HasOne("DocPrep.Domain.Supplementation.SupplementationQuestion", null)
                        .WithOne("Answer")
                        .HasForeignKey("DocPrep.Domain.Supplementation.SupplementationAnswer", "SupplementationQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationQuestion", b =>
                {
                    b.HasOne("DocPrep.Domain.Supplementation.SupplementationRound", null)
                        .WithMany("Questions")
                        .HasForeignKey("SupplementationRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationRound", b =>
                {
                    b.HasOne("DocPrep.Domain.Visits.VisitProcess", null)
                        .WithMany()
                        .HasForeignKey("VisitProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Tenancy.StaffRefreshToken", b =>
                {
                    b.HasOne("DocPrep.Domain.Tenancy.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Tenancy.StaffUser", b =>
                {
                    b.HasOne("DocPrep.Domain.Tenancy.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Visits.VisitProcess", b =>
                {
                    b.HasOne("DocPrep.Domain.Tenancy.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocPrep.Domain.Access.PatientIdentity", null)
                        .WithMany()
                        .HasForeignKey("PatientIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.InterviewDraft", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Answers");

                    b.Navigation("ChronicConditions");

                    b.Navigation("Clarifications");

                    b.Navigation("Medications");

                    b.Navigation("PatientQuestions");

                    b.Navigation("Symptoms");
                });

            modelBuilder.Entity("DocPrep.Domain.Interviews.Symptom", b =>
                {
                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("DocPrep.Domain.Observations.ObservationProposal", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationQuestion", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("DocPrep.Domain.Supplementation.SupplementationRound", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
